# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lj64XwdKo7QS3ufrcS5L7D1g3XWXLFYx
"""

import pandas as pd
import numpy as np

data1 = pd.read_csv("tableconvert_csv_so70jx.csv")
data1Mean = np.mean(data1)

pd.DataFrame.to_csv("data1Mean")

print(data1)
print(data1Mean)

